version: '3.7'

services:
  mysql:
    image: 'mysql'
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: akshay
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  config-server-ms:
    image: 'akshaybaviskar2804/config-server:latest'
    container_name: config-server
    ports:
      - 8080:8080
    depends_on:
      - service-reg
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - microservice-network

  service-reg:
    image: 'akshaybaviskar2804/service-reg:latest'
    container_name: service-reg
    ports:
      - 8761:8761
    depends_on:
      - rabbitmq
      - zipkin
      - mysql
    networks:
      - microservice-network
      - mysql

  companyms:
    image: 'akshaybaviskar2804/company:latest'
    container_name: company
    ports:
      - 8082:8082
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  jobms:
    image: 'akshaybaviskar2804/job:latest'
    container_name: job
    ports:
      - 8081:8081
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA.CLIENT.SERVICEURL.DEFAULTZONE=http://service-reg:8761

  reviewms:
    image: 'akshaybaviskar2804/review:latest'
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - service-reg
      - config-server-ms
    networks:
      - microservice-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservice-network
      - mysql

  zipkin:
    image: 'openzipkin/zipkin'
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - microservice-network
      - mysql

  gatewayms:
    image: 'akshaybaviskar2804/gateway:latest'
    container_name: gateway
    ports:
      - 8084:8084
    depends_on:
      - service-reg
    networks:
      - microservice-network
      - mysql
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  microservice-network:
    driver: bridge
  mysql:
    driver: bridge

volumes:
  mysql-data: